### ISSUE TITLE
Linking with libnuma fails

### ISSUE THREAD

**Issue by alexandermerritt** [lemonrock/libnuma-sys#1]
Linking does not succeed. Use of function 'mbind' results in:

`undefined reference to mbind`

This package may need to have a build script. See [here](http://doc.crates.io/build-script.html#case-study-linking-to-system-libraries) and [here](http://doc.crates.io/build-script.html#outputs-of-the-build-script).

**Comment by raphaelcohn** [comment]
Hmmm... I'm linking on Ubuntu 14.04 without issues. Do you have a test program you could paste as a gist? I've substantially re-worked this library, and, whilst it is quite buggy still, this really shouldn't happen...

**Comment by alexandermerritt** [comment]
Using the latest I do not have the linker issue anymore.
